ingress:
  enabled: true
  className: "nginx"
  annotations:    
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: home.dev.demo.catena-x.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: tls-secret
      hosts:
        - home.dev.demo.catena-x.net

  image:
    repository: ghcr.io/catenax-ng/k8s-helm-example
service:
  environment: "DEV"